---
version: "3.3"

services:
  fast_api_video_generator:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app/
    networks:
      - deploy_fast_api_project
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: video_db
    restart: always
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    networks:
      - deploy_fast_api_project
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-video_db}

networks:
  deploy_fast_api_project:
    driver: bridge
